### ISSUE TITLE
Scheduler policy was deprecated in 1.12, how to extend scheduler?

### ISSUE THREAD

**Issue by fanux** [kubernetes/kube-scheduler#1]
Scheduler policy was deprecated in 1.12? How can I use HTTP extender?
```
o.Deprecated.AddFlags(fs, &o.ComponentConfig)
```

https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/scheduler_extender.md

We need to extend scheduler badly...

**Comment by Huang-Wei** [comment]
@fanux We usually don't track issues here. Could you close this issue and move the discussion to kubernetes/kubernetes?
